name: CI Básico - Sprint 1 (Linter)

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

# Tareas
jobs:
  linter_python:
    name: Validar Sintaxis Python
    runs-on: ubuntu-latest

    steps:
      # Clonar el código del repositorio en el servidor de GitHub
      - name: Descargar el código
        uses: actions/checkout@v4

      # Preparar el entorno con Python
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Versión compatible con el backend

      # Instalar la herramienta de validación
      - name: Instalar Flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      # Ejecutar el linter para buscar errores críticos
      - name: Ejecutar revisión de sintaxis
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
